name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install

      - name: Build all packages
        run: npx nx run-many -t build --all

      - name: Type check (excluding atlassian-graphql)
        run: npx nx run-many -t typecheck --exclude=atlassian-graphql

      - name: Lint
        run: npx nx run-many -t lint --all

      - name: Run tests
        run: npm test
