name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build all packages
        run: npx nx run-many -t build --all

      - name: Type check
        run: npx nx run-many -t typecheck --all

      - name: Lint
        run: npx nx run-many -t lint --all

      - name: Run tests
        run: npm test

